### PR TITLE
Optimize cache generation

### PR DESCRIPTION
**Pull request by NikitaIvanovV**
Personally, I'd prefer quicker image loading despite having bigger cache, so this PR adds options for it.

Also, use identify instead of exiftool, it's much more quicker and comes with convert (AFAIK it's an ImageMagick utility).

### CODE REVIEW

**Comment by Naheel-Azawy** [comment]
Nice, thank you.
But I have a little concern regarding `identify`. I actually used to use it in the [early versions](https://github.com/Naheel-Azawy/stpv/blob/0f8bb28ece19c64607e017e158b8d3aab00a3f78/stpv#L239). But I switched to `exiftool` after realizing that `identify` reads the whole file. This means `identify` can be really slow for large files.
Here's an example:

```
Documents> ls -lh bliss.jpg The_Garden_of_earthly_delights.jpg
-rw-r--r-- 1 naheel wheel  50K Feb 27 03:45 bliss.jpg
-rw-r--r-- 1 naheel wheel 175M Nov  2  2020 The_Garden_of_earthly_delights.jpg
Documents>
Documents> time exiftool -S -ImageSize bliss.jpg
ImageSize: 800x600

________________________________________________________
Executed in  134.30 millis    fish           external
   usr time  123.02 millis  269.00 micros  122.75 millis
   sys time   10.03 millis  123.00 micros    9.91 millis

Documents> time identify -format '%w\n%h\n' bliss.jpg
800
600

________________________________________________________
Executed in   22.71 millis    fish           external
   usr time   14.81 millis  311.00 micros   14.50 millis
   sys time    5.95 millis  144.00 micros    5.81 millis

Documents>
Documents> time exiftool -S -ImageSize The_Garden_of_earthly_delights.jpg
ImageSize: 39137x22279

________________________________________________________
Executed in  141.94 millis    fish           external
   usr time  113.56 millis   34.00 micros  113.53 millis
   sys time   27.17 millis  485.00 micros   26.68 millis

Documents> time identify -format '%w\n%h\n' The_Garden_of_earthly_delights.jpg
39137
22279

________________________________________________________
Executed in   12.37 secs    fish           external
   usr time    9.27 secs  590.00 micros    9.27 secs
   sys time    3.03 secs    0.00 micros    3.03 secs

```

How about using both? Maybe we can check the file size and decide to use `identify` or `exiftool`. But that would need some trial and error to set a threshold I guess.

EDIT: Sorry for my slow response. It will probably take me some more time to get back. Thank you for your patience!

**Comment by NikitaIvanovV** [comment]
I've just read that there's [`-ping` option](https://imagemagick.org/script/command-line-options.php#ping) for identify, which makes it determine image characteristics efficiently. The docs don't clearly say what "efficiently" means but I presume it attempts to read the header first.

Could you try using the `-ping` option in your benchmark to see if it really improves anything?

**Comment by Naheel-Azawy** [comment]
Nice, I haven't noticed that option before.

```
Documents> time identify -ping -format '%w\n%h\n' The_Garden_of_earthly_delights.jpg
39137
22279

________________________________________________________
Executed in   14.30 millis    fish           external
   usr time   12.05 millis  382.00 micros   11.66 millis
   sys time    0.15 millis  150.00 micros    0.00 millis

Documents> time identify -ping -format '%w\n%h\n' bliss.jpg
800
600

________________________________________________________
Executed in   13.73 millis    fish           external
   usr time    4.68 millis  298.00 micros    4.38 millis
   sys time    7.51 millis  129.00 micros    7.39 millis
```

Now, I'd gladly come back to `identify`.

**Comment by NikitaIvanovV** [comment]
Wow, `-ping` works indeed! 👍

**Comment by Naheel-Azawy** [comment]
That looks great now, thanks. Merged!

**Pull request merged**
